use crate::theme3::{hex, TerminalColors, Theme, ThemeFamily, ThemeStyles};

pub fn ayu_family() -> ThemeFamily {
    ThemeFamily {
        id: "ayu_family".to_string(),
        name: "Ayu".into(),
        author: "dempfi".into(),
        themes: vec![
            // ayu_light(),
            ayu_mirage(),
            // ayu_dark(),
        ],
    }
}

fn ayu_mirage() -> Theme {
    Theme {
        id: "ayu_mirage".to_string(),
        name: "Ayu Mirage".into(),
        appearance: "Dark".to_string().into(),
        styles: ThemeStyles {
            background: todo!(),
            background_selected: todo!(),
            background_variant: todo!(),
            border: todo!(),
            border_selected: todo!(),
            border_variant: todo!(),
            button_background: todo!(),
            drag_target_background: todo!(),
            editor_active_line_background: todo!(),
            editor_active_line_number: todo!(),
            editor_active_wrap_guide: todo!(),
            editor_background: todo!(),
            editor_document_highlight_read_background: todo!(),
            editor_document_highlight_write_background: todo!(),
            editor_foreground: todo!(),
            editor_gutter_background: todo!(),
            editor_highlighted_line_background: todo!(),
            editor_invisible: todo!(),
            editor_line_number: todo!(),
            editor_occurrence: todo!(),
            editor_predictive: todo!(),
            editor_subheader_background: todo!(),
            editor_unreachable: todo!(),
            editor_wrap_guide: todo!(),
            foreground: todo!(),
            foreground_accent: todo!(),
            foreground_placeholder: todo!(),
            foreground_selected: todo!(),
            foreground_variant: todo!(),
            highlights: todo!(),
            input_background: todo!(),
            input_border: todo!(),
            modal_background: todo!(),
            pane_background: todo!(),
            pane_focused_border: todo!(),
            panel_background: todo!(),
            panel_button: todo!(),
            panel_focused_border: todo!(),
            player_host: todo!(),
            players: todo!(),
            popover_background: todo!(),
            popover_border: todo!(),
            scrollbar_thumb: todo!(),
            scrollbar_thumb_border: todo!(),
            scrollbar_track_background: todo!(),
            scrollbar_track_border: todo!(),
            search_match: todo!(),
            shadow: todo!(),
            state_focused: todo!(),
            state_selected: todo!(),
            status_bar_background: todo!(),
            status_conflict: todo!(),
            status_created: todo!(),
            status_deleted: todo!(),
            status_error: todo!(),
            status_hidden: todo!(),
            status_hint: todo!(),
            status_ignored: todo!(),
            status_info: todo!(),
            status_modified: todo!(),
            status_renamed: todo!(),
            status_success: todo!(),
            status_warning: todo!(),
            tab_active_background: todo!(),
            tab_bar_background: todo!(),
            tab_inactive_background: todo!(),
            terminal: todo!(),
            title_bar_background: todo!(),
            title_bar_button: todo!(),
            toolbar_background: todo!(),
            toolbar_button: todo!(),
        },
    }
}
